
# ModLoader
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

# The mod
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

issueTrackerURL="https://github.com/ActuallyPortals/ActuallySize/issues"

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="asi_banner.png"

# A text field displayed in the mod UI
credits="Shoutout to TitanicTerra for mod design discussions"

# A text field displayed in the mod UI
authors="${mod_authors}"

# The description text for the mod
description='''${mod_description}

Discord link for public server: [TBD]

ASI focuses on playing minecraft with friends of different sizes
✓ Pickup smaller entities and keep them as items (including other players!)
✓ Various uses for tinies such as companion, equipment, or snack
✓ Environmental buffs and nerfs for beegs and tinies
✓ Configure your playstyle in mods/config/actuallysize-config.toml
✓ Backend fixes for stuff that makes beeg or tiny play annoying

Mod Source: https://github.com/ActuallyPortals/actuallysize'''

# Dependency - Forge
[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

# Dependency - Minecraft
[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"